/* soapClient.cpp
   Generated by gSOAP 2.8.69 for service.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.69 2018-08-31 16:15:10 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___sunat__getStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__getStatus *ns1__getStatus_, ns1__getStatusResponse &ns1__getStatusResponse_)
{	struct __sunat__getStatus soap_tmp___sunat__getStatus;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://e-factura.sunat.gob.pe:443/ol-ti-itcpfegem/billService";
	if (soap_action == NULL)
		soap_action = "urn:getStatus";
	soap_tmp___sunat__getStatus.ns1__getStatus_ = ns1__getStatus_;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___sunat__getStatus(soap, &soap_tmp___sunat__getStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___sunat__getStatus(soap, &soap_tmp___sunat__getStatus, "-sunat:getStatus", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___sunat__getStatus(soap, &soap_tmp___sunat__getStatus, "-sunat:getStatus", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__getStatusResponse*>(&ns1__getStatusResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__getStatusResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getStatusResponse_.soap_get(soap, "ns1:getStatusResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___sunat__sendBill(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__sendBill *ns1__sendBill_, ns1__sendBillResponse &ns1__sendBillResponse_)
{	struct __sunat__sendBill soap_tmp___sunat__sendBill;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://e-factura.sunat.gob.pe:443/ol-ti-itcpfegem/billService";
	if (soap_action == NULL)
		soap_action = "urn:sendBill";
	soap_tmp___sunat__sendBill.ns1__sendBill_ = ns1__sendBill_;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___sunat__sendBill(soap, &soap_tmp___sunat__sendBill);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___sunat__sendBill(soap, &soap_tmp___sunat__sendBill, "-sunat:sendBill", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___sunat__sendBill(soap, &soap_tmp___sunat__sendBill, "-sunat:sendBill", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__sendBillResponse*>(&ns1__sendBillResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__sendBillResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__sendBillResponse_.soap_get(soap, "ns1:sendBillResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___sunat__sendPack(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__sendPack *ns1__sendPack_, ns1__sendPackResponse &ns1__sendPackResponse_)
{	struct __sunat__sendPack soap_tmp___sunat__sendPack;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://e-factura.sunat.gob.pe:443/ol-ti-itcpfegem/billService";
	if (soap_action == NULL)
		soap_action = "urn:sendPack";
	soap_tmp___sunat__sendPack.ns1__sendPack_ = ns1__sendPack_;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___sunat__sendPack(soap, &soap_tmp___sunat__sendPack);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___sunat__sendPack(soap, &soap_tmp___sunat__sendPack, "-sunat:sendPack", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___sunat__sendPack(soap, &soap_tmp___sunat__sendPack, "-sunat:sendPack", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__sendPackResponse*>(&ns1__sendPackResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__sendPackResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__sendPackResponse_.soap_get(soap, "ns1:sendPackResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___sunat__sendSummary(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__sendSummary *ns1__sendSummary_, ns1__sendSummaryResponse &ns1__sendSummaryResponse_)
{	struct __sunat__sendSummary soap_tmp___sunat__sendSummary;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://e-factura.sunat.gob.pe:443/ol-ti-itcpfegem/billService";
	if (soap_action == NULL)
		soap_action = "urn:sendSummary";
	soap_tmp___sunat__sendSummary.ns1__sendSummary_ = ns1__sendSummary_;
	soap_begin(soap);
	soap_set_version(soap, 1); /* SOAP1.1 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___sunat__sendSummary(soap, &soap_tmp___sunat__sendSummary);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___sunat__sendSummary(soap, &soap_tmp___sunat__sendSummary, "-sunat:sendSummary", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___sunat__sendSummary(soap, &soap_tmp___sunat__sendSummary, "-sunat:sendSummary", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__sendSummaryResponse*>(&ns1__sendSummaryResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__sendSummaryResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__sendSummaryResponse_.soap_get(soap, "ns1:sendSummaryResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
