-- MySQL Script generated by MySQL Workbench
-- Fri Apr 20 17:03:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema polleria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `polleria` ;

-- -----------------------------------------------------
-- Schema polleria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `polleria` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `polleria` ;

-- -----------------------------------------------------
-- Table `polleria`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`grupo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`grupo` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`item` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`item` (
  `nombre` VARCHAR(45) NOT NULL,
  `grupo_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  CONSTRAINT `fk_item_grupo1`
    FOREIGN KEY (`grupo_nombre`)
    REFERENCES `polleria`.`grupo` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_item_grupo1_idx` ON `polleria`.`item` (`grupo_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`persona` (
  `cod` VARCHAR(11) NOT NULL,
  `nombre` VARCHAR(145) NULL,
  `nombre_corto` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `telefono` VARCHAR(90) NULL,
  `celular` VARCHAR(90) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `email` VARCHAR(145) NULL,
  `estado_item_nombre` VARCHAR(45) NOT NULL,
  `tipo_item_nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(245) NULL,
  PRIMARY KEY (`cod`),
  CONSTRAINT `fk_persona_item1`
    FOREIGN KEY (`estado_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_persona_item2`
    FOREIGN KEY (`tipo_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_persona_item1_idx` ON `polleria`.`persona` (`estado_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_persona_item2_idx` ON `polleria`.`persona` (`tipo_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`direccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`direccion` (
  `domicilio_fiscal` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`domicilio_fiscal`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`divisa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`divisa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`divisa` (
  `fecha` FLOAT NOT NULL,
  `valor` FLOAT NULL,
  `moneda_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`),
  CONSTRAINT `fk_divisa_item1`
    FOREIGN KEY (`moneda_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_divisa_item1_idx` ON `polleria`.`divisa` (`moneda_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`impuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`impuesto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`impuesto` (
  `fecha` DATE NOT NULL,
  `valor` FLOAT NULL,
  `moneda_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`),
  CONSTRAINT `fk_impuesto_item1`
    FOREIGN KEY (`moneda_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_impuesto_item1_idx` ON `polleria`.`impuesto` (`moneda_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`comprobante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`comprobante` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`comprobante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  `serie` VARCHAR(4) NULL,
  `numero` INT NULL,
  `fecha_emision` DATETIME NULL,
  `anulado` TINYINT NULL,
  `pago_item_nombre` VARCHAR(45) NOT NULL,
  `estado_item_nombre` VARCHAR(45) NOT NULL,
  `operacion_item_nombre` VARCHAR(45) NOT NULL,
  `tipo_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comprobante_item1`
    FOREIGN KEY (`pago_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_item2`
    FOREIGN KEY (`estado_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_item3`
    FOREIGN KEY (`operacion_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_item4`
    FOREIGN KEY (`tipo_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item1_idx` ON `polleria`.`comprobante` (`pago_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item2_idx` ON `polleria`.`comprobante` (`estado_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item3_idx` ON `polleria`.`comprobante` (`operacion_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item4_idx` ON `polleria`.`comprobante` (`tipo_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`regimen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`regimen` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`regimen` (
  `fecha` DATE NOT NULL,
  `valor` FLOAT NULL,
  `regimen_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`),
  CONSTRAINT `fk_regimen_item1`
    FOREIGN KEY (`regimen_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_regimen_de_pago_item1_idx` ON `polleria`.`regimen` (`regimen_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`per_dir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`per_dir` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`per_dir` (
  `persona_cod` VARCHAR(11) NOT NULL,
  `direccion_domicilio_fiscal` VARCHAR(255) NOT NULL,
  `establecimiento_item_nombre` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_per_dir_direccion1`
    FOREIGN KEY (`direccion_domicilio_fiscal`)
    REFERENCES `polleria`.`direccion` (`domicilio_fiscal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_per_dir_item1`
    FOREIGN KEY (`establecimiento_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_per_dir_persona1`
    FOREIGN KEY (`persona_cod`)
    REFERENCES `polleria`.`persona` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_per_dir_direccion1_idx` ON `polleria`.`per_dir` (`direccion_domicilio_fiscal` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_per_dir_item1_idx` ON `polleria`.`per_dir` (`establecimiento_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_per_dir_persona1_idx` ON `polleria`.`per_dir` (`persona_cod` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`comprobante_has_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`comprobante_has_persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`comprobante_has_persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comprobante_id` INT NOT NULL,
  `persona_cod` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comprobante_has_persona_comprobante1`
    FOREIGN KEY (`comprobante_id`)
    REFERENCES `polleria`.`comprobante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_has_persona_persona1`
    FOREIGN KEY (`persona_cod`)
    REFERENCES `polleria`.`persona` (`cod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_persona_persona1_idx` ON `polleria`.`comprobante_has_persona` (`persona_cod` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_persona_comprobante1_idx` ON `polleria`.`comprobante_has_persona` (`comprobante_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`familia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`familia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(145) NOT NULL,
  `operacion_item_nombre` VARCHAR(45) NOT NULL,
  `x` INT NULL,
  `y` INT NULL,
  `font` VARCHAR(145) NULL,
  `color` VARCHAR(45) NULL,
  `background_color` VARCHAR(45) NULL,
  `estado_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_familia_item1`
    FOREIGN KEY (`operacion_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_familia_item2`
    FOREIGN KEY (`estado_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_familia_item1_idx` ON `polleria`.`familia` (`operacion_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_familia_item2_idx` ON `polleria`.`familia` (`estado_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(145) NOT NULL,
  `familia_id` INT NOT NULL,
  `operacion_item_nombre` VARCHAR(45) NOT NULL,
  `x` INT NULL,
  `y` INT NULL,
  `font` VARCHAR(145) NULL,
  `color` VARCHAR(45) NULL,
  `background_color` VARCHAR(45) NULL,
  `descripcion` VARCHAR(245) NULL,
  `precio` FLOAT NULL,
  `estado_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_producto_item1`
    FOREIGN KEY (`operacion_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_item2`
    FOREIGN KEY (`estado_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_familia1`
    FOREIGN KEY (`familia_id`)
    REFERENCES `polleria`.`familia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_producto_item1_idx` ON `polleria`.`producto` (`operacion_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_producto_item2_idx` ON `polleria`.`producto` (`estado_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_producto_familia1_idx` ON `polleria`.`producto` (`familia_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`comprobante_has_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`comprobante_has_producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`comprobante_has_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comprobante_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `unidad_item_nombre` VARCHAR(45) NOT NULL,
  `cantidad` FLOAT NULL,
  `precio` FLOAT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comprobante_has_producto_comprobante1`
    FOREIGN KEY (`comprobante_id`)
    REFERENCES `polleria`.`comprobante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_has_producto_item1`
    FOREIGN KEY (`unidad_item_nombre`)
    REFERENCES `polleria`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_has_producto_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `polleria`.`producto` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_producto_comprobante1_idx` ON `polleria`.`comprobante_has_producto` (`comprobante_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_producto_item1_idx` ON `polleria`.`comprobante_has_producto` (`unidad_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_producto_producto1_idx` ON `polleria`.`comprobante_has_producto` (`producto_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`datos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`datos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`datos` (
  `splitter_1` INT NULL,
  `splitter_2` INT NULL,
  `splitter_3` INT NULL,
  `familia_filas` INT NULL,
  `familia_columnas` INT NULL,
  `plato_filas` INT NULL,
  `plato_columnas` INT NULL,
  `clave_wifi` VARCHAR(45) NULL,
  `fondo_tapiz` VARCHAR(55) NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `nombre_UNIQUE` ON `polleria`.`usuario` (`nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`persona_has_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`persona_has_usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`persona_has_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_cod` VARCHAR(11) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_persona_has_usuario_persona1`
    FOREIGN KEY (`persona_cod`)
    REFERENCES `polleria`.`persona` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_persona_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `polleria`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_persona_has_usuario_persona1_idx` ON `polleria`.`persona_has_usuario` (`persona_cod` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_persona_has_usuario_usuario1_idx` ON `polleria`.`persona_has_usuario` (`usuario_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`ingrediente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`ingrediente` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `polleria`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polleria`.`pago` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `polleria`.`pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comprobante_id` INT NOT NULL,
  `persona_cod` VARCHAR(11) NOT NULL,
  `precio` FLOAT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pago_comprobante1`
    FOREIGN KEY (`comprobante_id`)
    REFERENCES `polleria`.`comprobante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pago_persona1`
    FOREIGN KEY (`persona_cod`)
    REFERENCES `polleria`.`persona` (`cod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_pago_comprobante1_idx` ON `polleria`.`pago` (`comprobante_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_pago_persona1_idx` ON `polleria`.`pago` (`persona_cod` ASC);

SHOW WARNINGS;
USE `polleria` ;

-- -----------------------------------------------------
-- procedure multiple_query
-- -----------------------------------------------------

USE `polleria`;
DROP procedure IF EXISTS `polleria`.`multiple_query`;
SHOW WARNINGS;

DELIMITER $$
USE `polleria`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `multiple_query`(m_query TEXT)
BEGIN
	/* INICIALIZACION*/
    SET @m_query:= m_query;
 
	label1: LOOP
		SET @pos:= LOCATE('&&END_QUERY&&', @m_query);
        SET @query_:= SUBSTRING(@m_query,1, @pos-1);
                
		
        PREPARE stmt1 FROM @query_;	
		EXECUTE stmt1;

		DEALLOCATE PREPARE stmt1;
        
        SET @m_query = SUBSTRING(@m_query, @pos+13);

		IF @m_query = '' THEN
		  LEAVE label1;
		END IF;			
	END LOOP label1;    
END$$

DELIMITER ;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
