-- MySQL Script generated by MySQL Workbench
-- Sun Mar  4 11:25:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bmkperu
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bmkperu` ;

-- -----------------------------------------------------
-- Schema bmkperu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bmkperu` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `bmkperu` ;

-- -----------------------------------------------------
-- Table `bmkperu`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`grupo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`grupo` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`item` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`item` (
  `nombre` VARCHAR(45) NOT NULL,
  `grupo_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  CONSTRAINT `fk_item_grupo1`
    FOREIGN KEY (`grupo_nombre`)
    REFERENCES `bmkperu`.`grupo` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_item_grupo1_idx` ON `bmkperu`.`item` (`grupo_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`persona` (
  `cod` VARCHAR(11) NOT NULL,
  `nombre` VARCHAR(145) NULL,
  `nombre_corto` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `telefono` VARCHAR(90) NULL,
  `celular` VARCHAR(90) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `email` VARCHAR(255) NULL,
  `estado_item_nombre` VARCHAR(45) NOT NULL,
  `tipo_item_nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(245) NULL,
  PRIMARY KEY (`cod`),
  CONSTRAINT `fk_persona_item1`
    FOREIGN KEY (`estado_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_persona_item2`
    FOREIGN KEY (`tipo_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_persona_item1_idx` ON `bmkperu`.`persona` (`estado_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_persona_item2_idx` ON `bmkperu`.`persona` (`tipo_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`divisa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`divisa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`divisa` (
  `fecha` FLOAT NOT NULL,
  `valor` FLOAT NULL,
  `moneda_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`),
  CONSTRAINT `fk_divisa_item1`
    FOREIGN KEY (`moneda_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_divisa_item1_idx` ON `bmkperu`.`divisa` (`moneda_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`impuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`impuesto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`impuesto` (
  `fecha` DATE NOT NULL,
  `valor` FLOAT NULL,
  `moneda_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`),
  CONSTRAINT `fk_impuesto_item1`
    FOREIGN KEY (`moneda_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_impuesto_item1_idx` ON `bmkperu`.`impuesto` (`moneda_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`comprobante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`comprobante` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`comprobante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  `serie` VARCHAR(4) NULL,
  `numero` INT NULL,
  `fecha_emision` DATETIME NULL,
  `anulado` TINYINT NULL,
  `pago_item_nombre` VARCHAR(45) NOT NULL,
  `estado_item_nombre` VARCHAR(45) NOT NULL,
  `operacion_item_nombre` VARCHAR(45) NOT NULL,
  `tipo_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comprobante_item1`
    FOREIGN KEY (`pago_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_item2`
    FOREIGN KEY (`estado_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_item3`
    FOREIGN KEY (`operacion_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_item4`
    FOREIGN KEY (`tipo_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item1_idx` ON `bmkperu`.`comprobante` (`pago_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item2_idx` ON `bmkperu`.`comprobante` (`estado_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item3_idx` ON `bmkperu`.`comprobante` (`operacion_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item4_idx` ON `bmkperu`.`comprobante` (`tipo_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`regimen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`regimen` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`regimen` (
  `fecha` DATE NOT NULL,
  `valor` FLOAT NULL,
  `regimen_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`),
  CONSTRAINT `fk_regimen_item1`
    FOREIGN KEY (`regimen_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_regimen_de_pago_item1_idx` ON `bmkperu`.`regimen` (`regimen_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`comprobante_has_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`comprobante_has_persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`comprobante_has_persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comprobante_id` INT NOT NULL,
  `persona_cod` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comprobante_has_persona_comprobante1`
    FOREIGN KEY (`comprobante_id`)
    REFERENCES `bmkperu`.`comprobante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_has_persona_persona1`
    FOREIGN KEY (`persona_cod`)
    REFERENCES `bmkperu`.`persona` (`cod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_persona_persona1_idx` ON `bmkperu`.`comprobante_has_persona` (`persona_cod` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_persona_comprobante1_idx` ON `bmkperu`.`comprobante_has_persona` (`comprobante_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`categoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(145) NULL,
  `x` INT NULL,
  `y` INT NULL,
  `font` VARCHAR(145) NULL,
  `color` VARCHAR(45) NULL,
  `background_color` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`medida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`medida` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`medida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unidad_item_nombre` VARCHAR(45) NOT NULL,
  `valor` FLOAT NULL,
  `tipo_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_medida_item1`
    FOREIGN KEY (`unidad_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_medida_item2`
    FOREIGN KEY (`tipo_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_medida_item1_idx` ON `bmkperu`.`medida` (`unidad_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_medida_item2_idx` ON `bmkperu`.`medida` (`tipo_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria_id` INT NOT NULL,
  `marca_item_nombre` VARCHAR(45) NOT NULL,
  `medida_id` INT NOT NULL,
  `nombre` VARCHAR(145) NULL,
  `x` INT NULL,
  `y` INT NULL,
  `font` VARCHAR(145) NULL,
  `color` VARCHAR(45) NULL,
  `background_color` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `bmkperu`.`categoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_item1`
    FOREIGN KEY (`marca_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_medida1`
    FOREIGN KEY (`medida_id`)
    REFERENCES `bmkperu`.`medida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_producto_categoria1_idx` ON `bmkperu`.`producto` (`categoria_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_producto_item1_idx` ON `bmkperu`.`producto` (`marca_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_producto_medida1_idx` ON `bmkperu`.`producto` (`medida_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`comprobante_has_plato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`comprobante_has_plato` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`comprobante_has_plato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comprobante_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` FLOAT NULL,
  `precio` FLOAT NULL DEFAULT 0.0,
  `peso` FLOAT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comprobante_has_plato_comprobante1`
    FOREIGN KEY (`comprobante_id`)
    REFERENCES `bmkperu`.`comprobante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_has_plato_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `bmkperu`.`producto` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_plato_comprobante1_idx` ON `bmkperu`.`comprobante_has_plato` (`comprobante_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_plato_producto1_idx` ON `bmkperu`.`comprobante_has_plato` (`producto_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`datos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`datos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`datos` (
  `splitter_1` INT NULL,
  `splitter_2` INT NULL,
  `splitter_3` INT NULL,
  `familia_filas` INT NULL,
  `familia_columnas` INT NULL,
  `plato_filas` INT NULL,
  `plato_columnas` INT NULL,
  `clave_wifi` VARCHAR(45) NULL,
  `fondo_tapiz` VARCHAR(55) NULL)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`insumo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`insumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(145) NULL,
  `medida_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_insumo_medida1`
    FOREIGN KEY (`medida_id`)
    REFERENCES `bmkperu`.`medida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_insumo_medida1_idx` ON `bmkperu`.`insumo` (`medida_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`producto_has_insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`producto_has_insumo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`producto_has_insumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NOT NULL,
  `insumo_id` INT NOT NULL,
  `cantidad` FLOAT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_producto_has_insumo_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `bmkperu`.`producto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_has_insumo_insumo1`
    FOREIGN KEY (`insumo_id`)
    REFERENCES `bmkperu`.`insumo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_producto_has_insumo_producto1_idx` ON `bmkperu`.`producto_has_insumo` (`producto_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_producto_has_insumo_insumo1_idx` ON `bmkperu`.`producto_has_insumo` (`insumo_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `nombre_UNIQUE` ON `bmkperu`.`usuario` (`nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`persona_has_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`persona_has_usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`persona_has_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_cod` VARCHAR(11) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_persona_has_usuario_persona1`
    FOREIGN KEY (`persona_cod`)
    REFERENCES `bmkperu`.`persona` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_persona_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bmkperu`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_persona_has_usuario_persona1_idx` ON `bmkperu`.`persona_has_usuario` (`persona_cod` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_persona_has_usuario_usuario1_idx` ON `bmkperu`.`persona_has_usuario` (`usuario_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`direccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`direccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`persona_has_direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`persona_has_direccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`persona_has_direccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_cod` VARCHAR(11) NOT NULL,
  `direccion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_persona_has_direccion_persona1`
    FOREIGN KEY (`persona_cod`)
    REFERENCES `bmkperu`.`persona` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_persona_has_direccion_direccion1`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `bmkperu`.`direccion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_persona_has_direccion_persona1_idx` ON `bmkperu`.`persona_has_direccion` (`persona_cod` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_persona_has_direccion_direccion1_idx` ON `bmkperu`.`persona_has_direccion` (`direccion_id` ASC);

SHOW WARNINGS;
USE `bmkperu` ;

-- -----------------------------------------------------
-- procedure multiple_query
-- -----------------------------------------------------

USE `bmkperu`;
DROP procedure IF EXISTS `bmkperu`.`multiple_query`;
SHOW WARNINGS;

DELIMITER $$
USE `bmkperu`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `multiple_query`(m_query TEXT)
BEGIN
	/* INICIALIZACION*/
    SET @m_query:= m_query;
 
	label1: LOOP
		SET @pos:= LOCATE('&&END_QUERY&&', @m_query);
        SET @query_:= SUBSTRING(@m_query,1, @pos-1);
                
		
        PREPARE stmt1 FROM @query_;	
		EXECUTE stmt1;

		DEALLOCATE PREPARE stmt1;
        
        SET @m_query = SUBSTRING(@m_query, @pos+13);

		IF @m_query = '' THEN
		  LEAVE label1;
		END IF;			
	END LOOP label1;    
END$$

DELIMITER ;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
