-- MySQL Script generated by MySQL Workbench
-- Sun Aug  6 10:59:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bmkperu
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bmkperu` ;

-- -----------------------------------------------------
-- Schema bmkperu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bmkperu` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `bmkperu` ;

-- -----------------------------------------------------
-- Table `bmkperu`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`grupo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`grupo` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`item` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`item` (
  `nombre` VARCHAR(45) NOT NULL,
  `grupo_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  CONSTRAINT `fk_item_grupo1`
    FOREIGN KEY (`grupo_nombre`)
    REFERENCES `bmkperu`.`grupo` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_item_grupo1_idx` ON `bmkperu`.`item` (`grupo_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`usuario` (
  `nombre` VARCHAR(145) NOT NULL,
  `pass` VARCHAR(145) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`persona` (
  `cod` VARCHAR(11) NOT NULL,
  `nombre` VARCHAR(145) NULL,
  `nombre_corto` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `telefono` VARCHAR(90) NULL,
  `celular` VARCHAR(90) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `estado_item_nombre` VARCHAR(45) NOT NULL,
  `usuario_nombre` VARCHAR(145) NULL,
  `tipo_item_nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(245) NULL,
  PRIMARY KEY (`cod`),
  CONSTRAINT `fk_persona_item1`
    FOREIGN KEY (`estado_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_persona_usuario1`
    FOREIGN KEY (`usuario_nombre`)
    REFERENCES `bmkperu`.`usuario` (`nombre`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_persona_item2`
    FOREIGN KEY (`tipo_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_persona_item1_idx` ON `bmkperu`.`persona` (`estado_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_persona_usuario1_idx` ON `bmkperu`.`persona` (`usuario_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_persona_item2_idx` ON `bmkperu`.`persona` (`tipo_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`direccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`direccion` (
  `domicilio_fiscal` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`domicilio_fiscal`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`familia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`familia` (
  `item_nombre` VARCHAR(45) NOT NULL,
  `x` INT NULL,
  `y` INT NULL,
  `font` VARCHAR(145) NULL,
  `color` VARCHAR(45) NULL,
  `background_color` VARCHAR(45) NULL,
  PRIMARY KEY (`item_nombre`),
  CONSTRAINT `fk_familia_item1`
    FOREIGN KEY (`item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`plato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`plato` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`plato` (
  `item_nombre` VARCHAR(45) NOT NULL,
  `familia_item_nombre` VARCHAR(45) NOT NULL,
  `marca_item_nombre` VARCHAR(45) NOT NULL,
  `unidad_item_nombre` VARCHAR(45) NOT NULL,
  `x` INT NULL,
  `y` INT NULL,
  `font` VARCHAR(145) NULL,
  `color` VARCHAR(45) NULL,
  `background_color` VARCHAR(45) NULL,
  `precio` FLOAT NULL,
  PRIMARY KEY (`item_nombre`),
  CONSTRAINT `fk_producto_item1`
    FOREIGN KEY (`marca_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_item3`
    FOREIGN KEY (`unidad_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plato_item1`
    FOREIGN KEY (`item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plato_familia1`
    FOREIGN KEY (`familia_item_nombre`)
    REFERENCES `bmkperu`.`familia` (`item_nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_producto_item1_idx` ON `bmkperu`.`plato` (`marca_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_producto_item3_idx` ON `bmkperu`.`plato` (`unidad_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_plato_familia1_idx` ON `bmkperu`.`plato` (`familia_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`divisa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`divisa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`divisa` (
  `fecha` FLOAT NOT NULL,
  `valor` FLOAT NULL,
  `moneda_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`),
  CONSTRAINT `fk_divisa_item1`
    FOREIGN KEY (`moneda_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_divisa_item1_idx` ON `bmkperu`.`divisa` (`moneda_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`impuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`impuesto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`impuesto` (
  `fecha` DATE NOT NULL,
  `valor` FLOAT NULL,
  `moneda_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`),
  CONSTRAINT `fk_impuesto_item1`
    FOREIGN KEY (`moneda_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_impuesto_item1_idx` ON `bmkperu`.`impuesto` (`moneda_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`comprobante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`comprobante` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`comprobante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `serie` VARCHAR(4) NULL,
  `numero` INT NULL,
  `fecha_emision` DATETIME NULL,
  `anulado` TINYINT NULL,
  `pago_item_nombre` VARCHAR(45) NOT NULL,
  `estado_item_nombre` VARCHAR(45) NOT NULL,
  `operacion_item_nombre` VARCHAR(45) NOT NULL,
  `tipo_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comprobante_item1`
    FOREIGN KEY (`pago_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_item2`
    FOREIGN KEY (`estado_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_item3`
    FOREIGN KEY (`operacion_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_item4`
    FOREIGN KEY (`tipo_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item1_idx` ON `bmkperu`.`comprobante` (`pago_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item2_idx` ON `bmkperu`.`comprobante` (`estado_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item3_idx` ON `bmkperu`.`comprobante` (`operacion_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_item4_idx` ON `bmkperu`.`comprobante` (`tipo_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`regimen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`regimen` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`regimen` (
  `fecha` DATE NOT NULL,
  `valor` FLOAT NULL,
  `regimen_item_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`),
  CONSTRAINT `fk_regimen_item1`
    FOREIGN KEY (`regimen_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_regimen_de_pago_item1_idx` ON `bmkperu`.`regimen` (`regimen_item_nombre` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`per_dir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`per_dir` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`per_dir` (
  `persona_cod` VARCHAR(11) NOT NULL,
  `direccion_domicilio_fiscal` VARCHAR(255) NOT NULL,
  `establecimiento_item_nombre` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_per_dir_direccion1`
    FOREIGN KEY (`direccion_domicilio_fiscal`)
    REFERENCES `bmkperu`.`direccion` (`domicilio_fiscal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_per_dir_item1`
    FOREIGN KEY (`establecimiento_item_nombre`)
    REFERENCES `bmkperu`.`item` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_per_dir_persona1`
    FOREIGN KEY (`persona_cod`)
    REFERENCES `bmkperu`.`persona` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_per_dir_direccion1_idx` ON `bmkperu`.`per_dir` (`direccion_domicilio_fiscal` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_per_dir_item1_idx` ON `bmkperu`.`per_dir` (`establecimiento_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_per_dir_persona1_idx` ON `bmkperu`.`per_dir` (`persona_cod` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`comprobante_has_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`comprobante_has_persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`comprobante_has_persona` (
  `comprobante_id` INT NOT NULL,
  `persona_cod` VARCHAR(11) NOT NULL,
  CONSTRAINT `fk_comprobante_has_persona_comprobante1`
    FOREIGN KEY (`comprobante_id`)
    REFERENCES `bmkperu`.`comprobante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_has_persona_persona1`
    FOREIGN KEY (`persona_cod`)
    REFERENCES `bmkperu`.`persona` (`cod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_persona_persona1_idx` ON `bmkperu`.`comprobante_has_persona` (`persona_cod` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_persona_comprobante1_idx` ON `bmkperu`.`comprobante_has_persona` (`comprobante_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`comprobante_has_plato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`comprobante_has_plato` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`comprobante_has_plato` (
  `comprobante_id` INT NOT NULL,
  `plato_item_nombre` VARCHAR(45) NOT NULL,
  `cantidad` FLOAT NULL,
  CONSTRAINT `fk_comprobante_has_plato_comprobante1`
    FOREIGN KEY (`comprobante_id`)
    REFERENCES `bmkperu`.`comprobante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comprobante_has_plato_plato1`
    FOREIGN KEY (`plato_item_nombre`)
    REFERENCES `bmkperu`.`plato` (`item_nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_plato_plato1_idx` ON `bmkperu`.`comprobante_has_plato` (`plato_item_nombre` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comprobante_has_plato_comprobante1_idx` ON `bmkperu`.`comprobante_has_plato` (`comprobante_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bmkperu`.`datos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bmkperu`.`datos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bmkperu`.`datos` (
  `splitter_1` INT NULL,
  `splitter_2` INT NULL,
  `splitter_3` INT NULL,
  `familia_filas` INT NULL,
  `familia_columnas` INT NULL,
  `plato_filas` INT NULL,
  `plato_columnas` INT NULL)
ENGINE = InnoDB;

SHOW WARNINGS;
USE `bmkperu` ;

-- -----------------------------------------------------
-- procedure multiple_query
-- -----------------------------------------------------

USE `bmkperu`;
DROP procedure IF EXISTS `bmkperu`.`multiple_query`;
SHOW WARNINGS;

DELIMITER $$
USE `bmkperu`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `multiple_query`(m_query TEXT)
BEGIN
	/* INICIALIZACION*/
    SET @m_query:= m_query;
 
	label1: LOOP
		SET @pos:= LOCATE('&&END_QUERY&&', @m_query);
        SET @query_:= SUBSTRING(@m_query,1, @pos-1);
                
		
        PREPARE stmt1 FROM @query_;	
		EXECUTE stmt1;

		DEALLOCATE PREPARE stmt1;
        
        SET @m_query = SUBSTRING(@m_query, @pos+13);

		IF @m_query = '' THEN
		  LEAVE label1;
		END IF;			
	END LOOP label1;    
END$$

DELIMITER ;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
