/* soapBillServicePortBindingProxy.h
   Generated by gSOAP 2.8.69 for C:\gsoap-2.8\gsoap\bin\win32\service.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapBillServicePortBindingProxy_H
#define soapBillServicePortBindingProxy_H
#include "soapH.h"
#include <winsock2.h>
#include <ws2tcpip.h>
#include <ws2spi.h>
    class SOAP_CMAC BillServicePortBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'BillServicePortBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in C:\gsoap-2.8\gsoap\bin\win32\service.h, if any
        /// Construct a proxy with new managing context
        BillServicePortBindingProxy();
        /// Copy constructor
        BillServicePortBindingProxy(const BillServicePortBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        BillServicePortBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        BillServicePortBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        BillServicePortBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        BillServicePortBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        BillServicePortBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~BillServicePortBindingProxy();
        /// Initializer used by constructors
        virtual void BillServicePortBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual BillServicePortBindingProxy *copy();
        /// Copy assignment
        BillServicePortBindingProxy& operator=(const BillServicePortBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'getStatus' (returns SOAP_OK or error code)
        virtual int getStatus(ns1__getStatus *ns1__getStatus_, ns1__getStatusResponse &ns1__getStatusResponse_)
        { return this->getStatus(NULL, NULL, ns1__getStatus_, ns1__getStatusResponse_); }
        virtual int getStatus(const char *soap_endpoint, const char *soap_action, ns1__getStatus *ns1__getStatus_, ns1__getStatusResponse &ns1__getStatusResponse_);
        /// Web service operation 'sendBill' (returns SOAP_OK or error code)
        virtual int sendBill(ns1__sendBill *ns1__sendBill_, ns1__sendBillResponse &ns1__sendBillResponse_)
        { return this->sendBill(NULL, NULL, ns1__sendBill_, ns1__sendBillResponse_); }
        virtual int sendBill(const char *soap_endpoint, const char *soap_action, ns1__sendBill *ns1__sendBill_, ns1__sendBillResponse &ns1__sendBillResponse_);
        /// Web service operation 'sendPack' (returns SOAP_OK or error code)
        virtual int sendPack(ns1__sendPack *ns1__sendPack_, ns1__sendPackResponse &ns1__sendPackResponse_)
        { return this->sendPack(NULL, NULL, ns1__sendPack_, ns1__sendPackResponse_); }
        virtual int sendPack(const char *soap_endpoint, const char *soap_action, ns1__sendPack *ns1__sendPack_, ns1__sendPackResponse &ns1__sendPackResponse_);
        /// Web service operation 'sendSummary' (returns SOAP_OK or error code)
        virtual int sendSummary(ns1__sendSummary *ns1__sendSummary_, ns1__sendSummaryResponse &ns1__sendSummaryResponse_)
        { return this->sendSummary(NULL, NULL, ns1__sendSummary_, ns1__sendSummaryResponse_); }
        virtual int sendSummary(const char *soap_endpoint, const char *soap_action, ns1__sendSummary *ns1__sendSummary_, ns1__sendSummaryResponse &ns1__sendSummaryResponse_);
    };
#endif
