os: Previous Visual Studio 2015

platform:
  - Win32
  - Win64

configuration:
  - Release

before_build:
  - if %platform%==Win32 set generator=Visual Studio 14
  - if %platform%==Win64 set generator=Visual Studio 14 Win64
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "%generator%" -DBUILD_PROG=1
  - msbuild leptonica.sln /p:Platform=%vcplatform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
